@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class node2 as "package  src.main.board" << package >>
class node0 as "package  src.main.game" << package >>
class node1 as "package  src.main.player" << package >>

@enduml
